# Generated by Django 4.2.3 on 2023-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0011_alter_category_image_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offer_zone',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
